### ISSUE TITLE
fix latex plot rendering

### ISSUE THREAD

**Issue by josephmje** [nipreps/nipreps-book#11]

**Comment by oesteban** [comment]
hahaha I just pinged you for this. I merged the PR because I think the GitHub action should work with the apt-get install I have added.

**Comment by josephmje** [comment]
I've configured it using the browser interface, which is probably not a good idea for the long term. You can also add a `netlify.toml` file to the repository's root directory that will take preference over the browser settings. Thanks for the GitHub action fix! I'll take a look and update the netlify configuration.

**Comment by oesteban** [comment]
I just added one more package to the apt-get.

**Comment by josephmje** [comment]
Looking like it's working now on the GitHub actions side!

**Comment by oesteban** [comment]
Yup, I found the missing package.
