### ISSUE TITLE
Review models section

### ISSUE THREAD

**Issue by oesteban** [nipreps/nipreps-book#14]
Hey Ariel, if you have a chance, please have a look into the models section (https://nipreps.org/nipreps-book/head-motion/models.html).

The code for that section (if you found time for crafting a PR) is here - https://github.com/nipreps/nipreps-book/blob/main/docs/head-motion/models.md

One thing that surprised me is that the tensor model seems to do pretty well, and the image looks definitely like the left-out. However, the DKI model seems very noisy. I'm afraid I might have gotten something wrong about it.

**Comment by arokem** [comment]
The short version is that I'm not surprised that DTI does pretty well. It's a good model for DWI signal in most voxels at least so long as the b-values are reasonably low (as we demonstrated [here](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0123272)). 

I am surprised to hear that DKI doesn't do so well. We've recently shown that, at least in one dataset, it can do better in this sense than DTI (that's figure 6 [here](https://www.biorxiv.org/content/10.1101/2021.03.04.433972v2.full.pdf)). One thing to consider is that DKI is more sensitive to artifacts such as Gibbs ringing. 

But I will also make a PR shortly.

**Comment by arokem** [comment]
I took a quick look at the DKI implementation. I can't see anything wrong with it. What kind of preprocessing did you do with that particular data? Any denoising or de-Gibbs-ing?

**Comment by oesteban** [comment]
No preprocessing at all. I was worried I could've done something wrong -
but if not, we'll revisit this later on. Judging by the incredible results
of DTI (this is 3-shells data), it makes sense to run one iteration of DTI
first and then maybe DKI. Thanks for taking a look!

**Comment by arokem** [comment]
Yes - let's explore later. I am also motivated to get SFM working 😄

**Comment by oesteban** [comment]
Great! Thanks for #16
