### ISSUE TITLE
Rendering SVGs in Jupyter Book

### ISSUE THREAD

**Issue by josephmje** [nipreps/nipreps-book#37]
The images from `niworkflows.viz.notebook` are static in the Jupyter Book. They should be changing upon hovering your cursor over them.

**Comment by oesteban** [comment]
hell yeah

**Comment by oesteban** [comment]
(I think just using html, if allowed, you can use <object> instead of <image> and it should work

**Comment by josephmje** [comment]
Thanks @oesteban. I played around with the HTML editor in Firefox and was able to get it by changing:

`<img alt="../_images/registration_15_0.svg" src="../_images/registration_15_0.svg">` to
`<object alt="../_images/registration_15_0.svg" type="image/svg+xml" data="../_images/registration_15_0.svg"></object>`

If I don't find a simpler solution, perhaps I can include something in the GitHub actions to make this edit on the htmls.

**Comment by josephmje** [comment]
Good point. Done!

WDYT: http://www.nipreps.org/nipreps-book/tutorial/registration.html

**Comment by oesteban** [comment]
Awesome!
